version: "3.2"

services:
  extraction-db:
    image: extraction-db
    build:
      context: ../db
      dockerfile: Dockerfile
    container_name: extraction-db
    expose:
      - 5432
    ports:
      - "5436:5432"
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_extractions:/var/lib/postgresql/data
    networks:
      - extractions

volumes:
  db_extractions:
    external: true

networks:
  extractions:
    external: true
